### PR TITLE
Register mccabe pytest marker

### PR DESCRIPTION
**Pull request by thijskramer**

### CODE REVIEW

**Comment by The-Compiler** [comment]
Thanks! I resolved a (trivial) conflict and adjusted the minimum pytest version: b174f8340a4a5bc55b6d4330845c67bd8375ad9f

Should I release v1.0 with the current master or do you have any other changes planned?

**Comment by thijskramer** [comment]
Thanks for merging! No I don't have any other changes planned, I just wanted to get rid of this warning: 

```
PytestUnknownMarkWarning: Unknown pytest.mark.mccabe - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
```

**Comment by thijskramer** [comment]
When could you release the current master as a 1.0 release on PyPI?

**Comment by The-Compiler** [comment]
Somewhen this week - probably today!

**Comment by The-Compiler** [comment]
I now released v1.0 with [some additional cleanups](https://github.com/The-Compiler/pytest-mccabe/compare/b174f8340a4a5bc55b6d4330845c67bd8375ad9f..v1.0) - thanks for your help!

**Pull request merged**
